services:
  node-agent:
    build: .
    container_name: marzban-node-agent
    restart: unless-stopped
    
    # Environment variables from .env file
    env_file: .env
    
    # Mount access.log as read-only
    volumes:
      - /var/lib/marzban-node/access.log:/var/lib/marzban/access.log:ro
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.path.append('/app/src'); from node_agent.config import ConfigService; import redis; config = ConfigService.load_from_env(); redis.Redis.from_url(config.central_redis_url).ping()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
        reservations:
          memory: 64M
          cpus: '0.1'

networks:
  default:
    name: marzban-node-agent
