services:
  node-agent:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: marzban-node-agent
    restart: unless-stopped
    user: root
    
    # Environment variables from .env file
    env_file:
      - ../config/.env
    
    # Mount access.log as read-only
    volumes:
      - /var/lib/marzban-node/access.log:/var/lib/marzban-node/access.log:ro
    
    # Network configuration (connect to existing marzban network if available)
    networks:
      - default
      - marzban-network
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
        reservations:
          memory: 64M
          cpus: '0.1'
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Health check
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import sys; sys.path.append('/app/src'); from node_agent.config import ConfigService; config = ConfigService.load_from_env(); print('OK')\" || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Labels for easier management
    labels:
      - "com.marzban.service=node-agent"
      - "com.marzban.version=1.0.0"

networks:
  marzban-network:
    external: true
    name: marzban-network

